language: java
jdk:
    - oraclejdk8
group: stable
dist: trusty
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
os: linux
script:
  - ./gradlew run
  - ./gradlew run --args="-orderProcessing"
  - ./gradlew run --args="-customer"
